from enum import Enum

from env_loader import load_env_file

load_env_file()

# Run
LAST_K_MESSAGES = 6
MAX_OUTPUT_TOKENS = 5000
MAX_OUTPUT_TOKENS_RETRY = 1600
TEMPERATURE = 0
OPENAI_TEXT_VERBOSITY = "low"
OPENAI_REASONING_EFFORT = "low"
MAX_ACTIONS_PER_TURN = 6
MAX_CONSECUTIVE_WORKER_ERRORS = 3
STOP_ON_ACTION_FAILURE = True
MAX_TURNS_PER_ROUND = 100

# Retries
MAX_STALLED_TURNS = 30
MAX_REPEAT_FAILURES_PER_ACTION = 3
MAX_CONSECUTIVE_VERIFICATION_TURNS = 1
MAX_CONSECUTIVE_LOW_IMPACT_REPEATS = 1
MAX_CONSECUTIVE_NOOP_UI_TURNS = 2
LLM_TIMEOUT_SECONDS = 60
AGENT_TURN_COOLDOWN_SECONDS = 5
DEBUG_HEARTBEAT_SECONDS = 5
PAGE_SETTLE_MS = 1000
ACTION_SETTLE_MS = 500
LLM_MAX_RETRIES = 3
LLM_RETRY_BASE_DELAY_S = 1.0
LLM_RETRY_MAX_DELAY_S = 30.0
LLM_RETRY_JITTER = 0.25

# Logging
LOG_PROMPTS = True
MAX_PROMPT_LOG_CHARS = 0
LOG_OBSERVATIONS = True
MAX_OBSERVATION_LOG_ELEMENTS = 60
MAX_OBSERVATION_VISIBLE_TEXT_CHARS = 2000
MAX_OBSERVATION_LOG_CHARS = 0
MAX_OBSERVATION_TARGET_SURFACES = 8
MAX_OBSERVATION_SURFACE_ANCHORS = 8
MAX_OBSERVATION_PROMOTED_ANCHORS = 20
STUCK_SCREENSHOT_THRESHOLD = 2

# Memory bounds
MAX_MESSAGES_RETAINED = 120  # rolling window for state.messages
MAX_FAILURE_COUNT_ENTRIES = 60  # cap on failure_counts dict size

REQUIRED_AGENT_KEYS = {"name", "provider", "model", "system_prompt"}


class Provider(str, Enum):
    OPENAI = "openai"
    DEEPSEEK = "deepseek"
    GEMINI = "gemini"


from village.prompts import AGENT_NAMES, build_prompt

AGENTS: list[dict] = [
    {
        "name": name,
        "provider": Provider.GEMINI,
        "model": "gemini-3-flash-preview",
        "system_prompt": build_prompt(name),
    }
    for name in AGENT_NAMES
]
